"""initial application tables

Revision ID: 4ad73cf6e7a2
Revises: 
Create Date: 2026-10-02 17:58:20.889334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ad73cf6e7a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event', sa.Enum('login_success', 'login_failure', 'login_locked', 'logout', name='audit_event'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_log'))
    )
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index('ix_admin_audit_log_event_created_at', 'admin_audit_log', ['event', 'created_at'], unique=False)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('shopify_draft_order_id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_order_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('awaiting_payment', 'paid', 'cancelled', 'expired', name='checkout_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_checkout_sessions_total_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_sessions')),
    sa.UniqueConstraint('reference', name=op.f('uq_checkout_sessions_reference')),
    sa.UniqueConstraint('shopify_draft_order_id', name=op.f('uq_checkout_sessions_shopify_draft_order_id')),
    sa.UniqueConstraint('shopify_order_id', name=op.f('uq_checkout_sessions_shopify_order_id'))
    )
    op.create_index('ix_checkout_sessions_status_created_at', 'checkout_sessions', ['status', 'created_at'], unique=False)
    op.create_table('saved_designs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_key', sa.String(length=64), nullable=False),
    sa.Column('shopify_product_handle', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('font', sa.String(length=60), nullable=True),
    sa.Column('text_color', sa.String(length=32), nullable=True),
    sa.Column('print_size', sa.String(length=20), nullable=True),
    sa.Column('placement', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_designs'))
    )
    op.create_index('ix_saved_designs_owner_key_created_at', 'saved_designs', ['owner_key', 'created_at'], unique=False)
    op.create_table('print_designs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checkout_session_id', sa.Uuid(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('shopify_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('font', sa.String(length=60), nullable=False),
    sa.Column('text_color', sa.String(length=32), nullable=False),
    sa.Column('print_size', sa.String(length=20), nullable=False),
    sa.Column('placement', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_index >= 0', name=op.f('ck_print_designs_line_index_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_print_designs_quantity_positive')),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], name=op.f('fk_print_designs_checkout_session_id_checkout_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_designs')),
    sa.UniqueConstraint('checkout_session_id', 'line_index', name='uq_print_designs_session_line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_designs')
    op.drop_index('ix_saved_designs_owner_key_created_at', table_name='saved_designs')
    op.drop_table('saved_designs')
    op.drop_index('ix_checkout_sessions_status_created_at', table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index('ix_admin_audit_log_event_created_at', table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
    sa.Enum(name='checkout_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_event').drop(op.get_bind(), checkfirst=True)
